site_name: "Qualidade de Software - T02 - Dorothy Johnson"
site_url: "https://fcte-qualidade-de-software-1.github.io/2025-1-T02-DOROTHY-JOHNSON/"
repo_url: "https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T02-DOROTHY-JOHNSON"

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - Fase 1:
      - Requisitos de Avalição: requisito_avaliacao/req.md
  - Fase 2: 
    - Definição: gqm/definition.md
    - Níveis de pontuação das métricas: gqm/niveis_pontuacao.md
    - Critérios para julgamento: gqm/criterio_julgamento.md
  - Fase 3:
    - Plano de Avaliação: avaliacao/plano.md
  - Fase 4:
    - Coleta de Dados:
      - Manutenibilidade: execucao/coleta_dados/manutenibilidade.md
      - Efetividade, eficiência e satisfação: execucao/coleta_dados/usabilidade.md
    - Comparar com Critérios: execucao/comparar.md
    - Julgar os Resultados: execucao/julgar_cri.md
    - Ações de Melhoria: execucao/acoes_melhoria.md
    - Q-Rapids: execucao/qrapids.md
  - Gestão de Projeto:
    - Metodologia: gestao/metodologia.md
    - Desempenho de Processos: gestao/desempenho.md
    - Calendário e Progresso: gestao/calendario.md
    - Recursos e Custos: gestao/recursos.md
  - Entregas: entregas/entregas.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - table-reader