discovery.type: single-node
xpack.security.enabled: false
xpack.security.transport.filter.allow: _all
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false
network.host: 0.0.0.0